title:       Nova Patch
email:       nova.patch@gmail.com
description: Personal website of Nova Patch, with writing, research, talks, and projects.
baseurl:     ""
url:         https://novapatch.ie
github:      patch
twitter:     novapatch
instagram:   novapatch
linkedin:    novapatch
encoding:    utf-8
markdown:    kramdown
timezone:    Europe/Dublin
locales:
  en: en_IE
  eo: eo_001
  ga: ga_IE
  nn: nn_NO
about:
  en: about
  eo: pri
  ga: fúm
  nn: om
